### ISSUE TITLE
Token bug

### ISSUE THREAD

**Issue by Anericokakai** [Anericokakai/Farm-Digital#27]
when  a user logs in with an account with the verified field set to false a token is still generate  but it is not supposed

**Comment by Bobcodiz** [comment]
> when a user logs in with an account with the verified field set to false a token is still generate but it is not supposed

where exactly

**Comment by Anericokakai** [comment]
## error on line  on line 80 in the user Registrationservice class
>we are not supposed not supposed to return a token  in the  user who is  who is not verified 

***exact code with the error***
```java
    public String authenticateauser(AuthenticationDto req) {

        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(
                        req.getEmail(),
                        req.getPassword()
                )
        );

        Farmer user;
        if (farmerRepository.findByEmail(req.getEmail()).isPresent()) {
            user = farmerRepository.findByEmail(req.getEmail()).get();
        } else {
            throw new EntityNotFoundException("invalid login credentials");
        }


        if(!user.isVerified()){
            //        ! validate emails for the users;
            emailComposer.sendVerificationEmail(user.getEmail());
            return "you have not verified your account , please check your email to verify your account!! ";
        }
//       Generate token
        return jwtServices.generateAToken(user);

    }
```

**Comment by Bobcodiz** [comment]
> when a user logs in with an account with the verified field set to false a token is still generate but it is not supposed



> ## error on line on line 80 in the user Registrationservice class
> 
> > we are not supposed not supposed to return a token  in the  user who is  who is not verified
> 
> _**exact code with the error**_
> 
> ```java
>     public String authenticateauser(AuthenticationDto req) {
> 
>         authenticationManager.authenticate(
>                 new UsernamePasswordAuthenticationToken(
>                         req.getEmail(),
>                         req.getPassword()
>                 )
>         );
> 
>         Farmer user;
>         if (farmerRepository.findByEmail(req.getEmail()).isPresent()) {
>             user = farmerRepository.findByEmail(req.getEmail()).get();
>         } else {
>             throw new EntityNotFoundException("invalid login credentials");
>         }
> 
> 
>         if(!user.isVerified()){
>             //        ! validate emails for the users;
>             emailComposer.sendVerificationEmail(user.getEmail());
>             return "you have not verified your account , please check your email to verify your account!! ";
>         }
> //       Generate token
>         return jwtServices.generateAToken(user);
> 
>     }
> ```
