### ISSUE TITLE
FarmerRegistrationDto

### ISSUE THREAD

**Issue by Bobcodiz** [Anericokakai/Farm-Digital#28]
Response file saved...INVALID RESPONSE
# HTTP response does not seem okay
```json
{
  "password": "password must contain least 8 character with an upper case , a special character(!,@,$,&,%) and a number ",
  "phoneNumber": "length must be between 10 and 12",
  "name": "name cannot be empty"
}
```
Response file saved.
> 2023-11-23T184754.401.json
I do not understand why i get the response 'Response file saved' yet the input values lead to exceptions.
The code is running even after the exceptions are caught...Aneriko please clarify

**Comment by Anericokakai** [comment]
> Response file saved...INVALID RESPONSE
> 
> # HTTP response does not seem okay
> ```json
> {
>   "password": "password must contain least 8 character with an upper case , a special character(!,@,$,&,%) and a number ",
>   "phoneNumber": "length must be between 10 and 12",
>   "name": "name cannot be empty"
> }
> ```
> 
> Response file saved.
> 
> > 2023-11-23T184754.401.json
> > I do not understand why i get the response 'Response file saved' yet the input values lead to exceptions.
> > The code is running even after the exceptions are caught...Aneriko please clarify
## Why is the file saved shown on your terminal
I will try to clarify the issue , when a request is send using the internal http client avialble in intelij we need to keep tack of the response sent back by the request thats why you are getting this message 
![why file saved](https://github.com/Anericokakai/AgriConnect/assets/119412102/36972f3e-8b8b-4e25-9287-afe04c9671ee)
notice in the image above we are saving the response in a json called `` 2023-11-23T203325.403.json`` but the json  response it self says that   the token is expired so focus on the json message and not where it is being saved
